/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BButton: typeof import('bootstrap-vue-next')['BButton']
    BCollapse: typeof import('bootstrap-vue-next')['BCollapse']
    BDropdown: typeof import('bootstrap-vue-next')['BDropdown']
    BDropdownDivider: typeof import('bootstrap-vue-next')['BDropdownDivider']
    BDropdownItem: typeof import('bootstrap-vue-next')['BDropdownItem']
    BFormCheckbox: typeof import('bootstrap-vue-next')['BFormCheckbox']
    BFormInput: typeof import('bootstrap-vue-next')['BFormInput']
    BFormTextarea: typeof import('bootstrap-vue-next')['BFormTextarea']
    BInputGroup: typeof import('bootstrap-vue-next')['BInputGroup']
    BInputGroupText: typeof import('bootstrap-vue-next')['BInputGroupText']
    BListGroup: typeof import('bootstrap-vue-next')['BListGroup']
    BListGroupItem: typeof import('bootstrap-vue-next')['BListGroupItem']
    BModal: typeof import('bootstrap-vue-next')['BModal']
    BToastOrchestrator: typeof import('bootstrap-vue-next')['BToastOrchestrator']
    Card: typeof import('./src/components/Card.vue')['default']
    CardDecklist: typeof import('./src/components/CardDecklist.vue')['default']
    CardDetail: typeof import('./src/components/CardDetail.vue')['default']
    DeckProba: typeof import('./src/components/DeckProba.vue')['default']
    DeckStats: typeof import('./src/components/DeckStats.vue')['default']
    Loader: typeof import('./src/components/icons/Loader.vue')['default']
    Logo: typeof import('./src/components/icons/Logo.vue')['default']
    Menu: typeof import('./src/components/Menu.vue')['default']
    PAccueil: typeof import('./src/components/PAccueil.vue')['default']
    PCartes: typeof import('./src/components/PCartes.vue')['default']
    PDeckBuilder: typeof import('./src/components/PDeckBuilder.vue')['default']
    PDecklists: typeof import('./src/components/PDecklists.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Test: typeof import('./src/components/Test.vue')['default']
  }
  export interface ComponentCustomProperties {
    vBToggle: typeof import('bootstrap-vue-next')['vBToggle']
  }
}
