/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Accueil: typeof import('./src/components/Accueil.vue')['default']
    AuthDiscord: typeof import('./src/components/AuthDiscord.vue')['default']
    BButton: typeof import('bootstrap-vue-next')['BButton']
    BCollapse: typeof import('bootstrap-vue-next')['BCollapse']
    BFormCheckbox: typeof import('bootstrap-vue-next')['BFormCheckbox']
    BFormInput: typeof import('bootstrap-vue-next')['BFormInput']
    BInputGroup: typeof import('bootstrap-vue-next')['BInputGroup']
    BLink: typeof import('bootstrap-vue-next')['BLink']
    BModal: typeof import('bootstrap-vue-next')['BModal']
    Card: typeof import('./src/components/Card.vue')['default']
    CardDecklist: typeof import('./src/components/CardDecklist.vue')['default']
    CardDetail: typeof import('./src/components/CardDetail.vue')['default']
    Collection: typeof import('./src/components/Collection.vue')['default']
    copy: typeof import('./src/components/Card copy.vue')['default']
    DeckBuilder: typeof import('./src/components/DeckBuilder.vue')['default']
    DeckStats: typeof import('./src/components/DeckStats.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    Loader: typeof import('./src/components/icons/Loader.vue')['default']
    Logo: typeof import('./src/components/icons/Logo.vue')['default']
    Menu: typeof import('./src/components/Menu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Test: typeof import('./src/components/Test.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
  export interface ComponentCustomProperties {
    vBModal: typeof import('bootstrap-vue-next')['vBModal']
    vBToggle: typeof import('bootstrap-vue-next')['vBToggle']
  }
}
